# Generated by Django 4.1.7 on 2023-02-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_personaldocument_relateddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='relateddocument',
            name='personaldoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.personaldocument'),
            preserve_default=False,
        ),
    ]
